# Generated by Django 5.0.6 on 2024-07-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('presentacion', models.CharField(max_length=20)),
                ('stockM', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('proveedor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacion', models.CharField(max_length=100)),
            ],
        ),
    ]
