# Generated by Django 5.0.6 on 2024-07-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='observacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
