# Generated by Django 5.0.6 on 2024-07-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_alter_producto_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
