# Generated by Django 5.0.1 on 2024-08-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0002_detallefactura_devuelto'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='cantidad_devuelta',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
