# Generated by Django 5.0.1 on 2024-10-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0003_detallefactura_cantidad_devuelta'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='pagoElectronico',
            field=models.BooleanField(default=False),
        ),
    ]
