# Generated by Django 5.0.1 on 2024-10-05 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuracion', '0002_costosfrecuentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='CostosFrecuentes',
        ),
        migrations.RemoveField(
            model_name='costos',
            name='frecuente',
        ),
        migrations.AddField(
            model_name='costos',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Configuracion.tipos'),
        ),
    ]
