# Generated by Django 5.0.1 on 2024-10-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuracion', '0003_tipos_delete_costosfrecuentes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipos',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
