# Generated by Django 5.0.1 on 2024-10-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuracion', '0004_tipos_eliminado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('porcentaje', models.DecimalField(decimal_places=5, max_digits=15)),
                ('eliminado', models.BooleanField(default=False)),
            ],
        ),
    ]
