# Generated by Django 5.0.1 on 2024-10-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuracion', '0005_parametros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(max_length=255)),
                ('NIT', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('correoElectronico', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=255)),
            ],
        ),
    ]
