# Generated by Django 5.0.1 on 2024-10-31 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuracion', '0006_organizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='costos',
            name='ingreso_egreso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
