# Generated by Django 5.0.1 on 2024-10-31 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuracion', '0007_costos_ingreso_egreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costos',
            name='ingreso_egreso',
            field=models.BooleanField(default=False),
        ),
    ]
