# Generated by Django 5.0.1 on 2024-10-31 01:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuracion', '0008_alter_costos_ingreso_egreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costos',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
