# Generated by Django 5.0.6 on 2024-07-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0002_empleado_cajadecompensacion_empleado_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
