# Generated by Django 5.0.6 on 2024-07-02 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Proveedor',
        ),
    ]
