# Generated by Django 5.0.6 on 2024-07-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0002_rename_producto_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
