# Generated by Django 5.0.1 on 2024-09-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0004_reabastecimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reabastecimiento',
            name='producto',
        ),
    ]
