# Generated by Django 5.0.1 on 2024-09-10 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_alter_producto_proveedor'),
        ('Proveedores', '0005_remove_reabastecimiento_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reabastecimiento',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='reabastecimiento',
            name='fechaEsperada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reabastecimiento',
            name='fechaLlegada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReabastecimientoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('credito', models.BooleanField(default=False)),
                ('eliminado', models.BooleanField(default=False)),
                ('observaciones', models.CharField(max_length=200)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.producto')),
                ('reabastecimiento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proveedores.reabastecimiento')),
            ],
        ),
    ]
